---
title: "OUTPUTS READ ME"
author: "Kristen E. Dybala"
date: "May 31, 2019"
output: html_document
---

This directory contains key results from the bioenergetics analysis of the impacts of incentive programs on meeting shorebird population objectives, in each shorebird non-breeding season from 2013-14 through 2016-17. 


### habitat_daily_stats.csv

This file contains estimates of the daily extent of flooded habitat available in the Central Valley by land cover type, including separate estimates for both total open water and accessible water (i.e., <10cm deep and accessible to most shorebirds). The table can be thought of as 2 parts (one for open water and one for accessible water), each of which is subdivided into 4 parts (one for each non-breeding season).

**Description of fields:**

* __group:__ label identifying shorebird non-breeding season; 4 options: 2013-14, 2014-15, 2015-16, 2016-17
* __time:__ integer identifying the day of the shorebird non-breeding season, where day 1 = July 1; ranges 1 - 319
* __corn:__ estimated hectares of fields planted with corn that are flooded on each day
* __other:__ estimated hectares of fields planted with "other" suitable crops that are flooded on each day; see Dybala et al. 2017 SFEWS for a list of "other" crops
* __perm:__ estimated hectares of permanent/semi-permanent managed wetlands that are flooded on each day
* __rice:__ estimated hectares of fields planted with rice that are flooded on each day
* __seas:__ estimated hectares of seasonal managed wetlands that are flooded on each day
* __br_fall:__ estimated hectares of fields enrolled in fall Bird Returns program and flooded on each day
* __br_spring:__ estimated hectares of fields enrolled in spring (or winter) Bird Returns program and flooded on each day
* __whep_fall:__ estimated hectares of fields enrolled in WHEP fall flooding practice and currently flooded on each day
* __whep_vardd:__ estimated hectares of fields enrolled in WHEP variable drawdown practice and currently flooded on each day
* __watertype:__ label identifying whether the area flooded represents total open water (open) or only shallow water accessible to shorebirds (accessible); 2 options: open or accessible


### bioenergetics_results_energy.csv

This file contains the main results of the bioenergetics analysis, including the daily energy requirements (kJ) of the shorebird population, the daily energy supply available, and the energy shortfall as the difference between the two. This table can be thought of as 2 parts (one for the shorebird population objectives and one for the baseline population size), each of which is subdivided into 3 parts representing different scenarios: including all incentive programs, excluding all incentive programs, and including only the fall incentive programs (i.e. br_fall and whep_fall). Each of these individual scenarios is further subdivided into 4 parts representing each non-breeding season.

**Description of fields:**

* __scenario:__ label identifying which combination of population objectives and incentive scenario is represented; 6 options:__ obj_det (population objectives, all incentives), obj_det2 (population objectives, no incentives), obj_det3 (population objectives, only fall incentives), obs_det (baseline population, all incentives), obs_det2 (baseline population, no incentives), obs_det3 (baseline population, only fall incentives)
* __group:__ label identifying shorebird non-breeding season; 4 options: 2013-14, 2014-15, 2015-16, 2016-17
* __time:__ integer identifying the day of the shorebird non-breeding season, where day 1 = July 1; ranges 1 - 319
* __DER:__ daily energy requirement of the shorebird population
* __supply:__ daily total energy supply across all flooded habitats included in the scenario
* __accessible:__ daily total energy supply in accessible flooded habitats
* __shortfall:__ daily energy shortfall, calculated as the difference between DER and accessible; values > 0 indicate an energy shortfall
* __incentives:__ label identifying which incentive programs are included in the scenario, corresponds to the scenario field above; 3 options: all, none, and fall_only
* __population:__ label identifying which population objectives are included in the scenario, corresponds to the scenario field above; 2 options: objectives or baseline


### bioenergetics_energy_consumed.csv

This file provides further insights into the bioenergetics analysis, showing the daily amount of energy (kJ) estimated to be consumed in each land cover type. This amount reflects the assumption of an ideal free distribution of the shorebird daily energy requirements across all accessible flooded habitat available on that day, according to the estimated average energy density remaining in each habitat. (However, the daily energy consumed in each land cover type cannot exceed the total amount of energy accessible in each land cover type.) This table can be used to examine the relative contributions of each land cover type to the total shorebird energy needs over the entire non-breeding season. As above, this table can be thought of as 2 parts (one for the shorebird population objectives and one for the baseline population size), each of which is subdivided into 3 parts representing different scenarios: including all incentive programs, excluding all incentive programs, and including only the fall incentive programs (i.e. br_fall and whep_fall). Each of these individual scenarios is further subdivided into 4 parts representing each non-breeding season.

**Description of fields:**

* __scenario:__ label identifying which combination of population objectives and incentive scenario is represented; 6 options:__ obj_det (population objectives, all incentives), obj_det2 (population objectives, no incentives), obj_det3 (population objectives, only fall incentives), obs_det (baseline population, all incentives), obs_det2 (baseline population, no incentives), obs_det3 (baseline population, only fall incentives)
* __group:__ label identifying shorebird non-breeding season; 4 options:__ 2013-14, 2014-15, 2015-16, 2016-17
* __time:__ integer identifying the day of the shorebird non-breeding season, where day 1 = July 1; ranges 1 - 319
* __corn:__ estimated energy consumed in fields planted with corn that are flooded on each day
* __other:__ estimated energy consumed in fields planted with "other" suitable crops that are flooded on each day
* __perm:__ estimated energy consumed in permanent/semi-permanent managed wetlands that are flooded on each day
* __rice:__ estimated energy consumed in fields planted with rice that are flooded on each day
* __seas:__ estimated energy consumed in seasonal managed wetlands that are flooded on each day
* __br_fall:__ estimated energy consumed in fields enrolled in fall Bird Returns program and flooded on each day
* __br_spring:__ estimated energy consumed in fields enrolled in spring (or winter) Bird Returns program and flooded on each day
* __whep_fall:__ estimated energy consumed in fields enrolled in WHEP fall flooding practice and currently flooded on each day
* __whep_vardd:__ estimated energy consumed in fields enrolled in WHEP variable drawdown practice and currently flooded on each day
* __incentives:__ label identifying which incentive programs are included in the scenario, corresponds to the scenario field above; 3 options: all, none, and fall_only
* __population:__ label identifying which population objectives are included in the scenario, corresponds to the scenario field above; 2 options: objectives or baseline
